# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cxxtitable <- function(sig) {
    .Call('smashr_cxxtitable', PACKAGE = 'smashr', sig)
}

cxxtirtable <- function(sig) {
    .Call('smashr_cxxtirtable', PACKAGE = 'smashr', sig)
}

cxxreverse_gwave <- function(estimate, pmat, qmat) {
    .Call('smashr_cxxreverse_gwave', PACKAGE = 'smashr', estimate, pmat, qmat)
}

cxxreverse_gvwave <- function(estimate, pmat, qmat) {
    .Call('smashr_cxxreverse_gvwave', PACKAGE = 'smashr', estimate, pmat, qmat)
}

cxxSParentTItable <- function(sig) {
    .Call('smashr_cxxSParentTItable', PACKAGE = 'smashr', sig)
}

cxxreverse_pwave <- function(estimate, pmat, qmat) {
    .Call('smashr_cxxreverse_pwave', PACKAGE = 'smashr', estimate, pmat, qmat)
}

